# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClientServer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'RealmSwift'
  # Pods for ClientServer

  target 'ClientServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClientServerUITests' do
    # Pods for testing
  end

end
